services:
  {% if cookiecutter.database == 'postgresql' -%}
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  {%- endif %}

volumes:
  {% if cookiecutter.database == 'postgresql' -%}
  postgres-data:
  {%- endif %}